title: EEA aa2025-2026
description: Tutorial for Bioinformatic Analysis of Epigenetics Data
theme: just-the-docs
color_scheme: "light"
nav_enabled: true
back_to_top: true
back_to_top_text: "Back to top"
exclude: 
  - "backup/"


#url: https://gabbo89.github.io/EEA2025-2026
#"https://www.sisfvg.it/sites/default/files/logoUniud-small.png"
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.png"

url: https://gabbo89.github.io/
baseurl: "/EEA2025-2026"

##aux_links:
##  Template Repository: https://github.com/just-the-docs/just-the-docs-template
#aux_links:
#  "Analisi di Dati Epigenetici on GitHub":
#    - "//github.com/gabbo89/EEA2025"
aux_links: true
   #"<button id='theme-toggle' class='btn js-toggle-dark-mode' onclick='modeSwitcher()'>Toggle Theme</button>"
#  "Preview dark color scheme":

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
#color_scheme: nil
#remote_theme: pdmosses/just-the-docs@light-switch

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
    opacity: 0.3
  success:
    title: Success
    color: green
  note:
    title: Note
    color: purple
    opacity: 0.3
  warning:
    title: Warning
    color: red
  failed:
    title: Failed
    color: grey-dk

footer_content: "Copyright &copy; 2026 Gabriele Magris."

# For copy button on code
enable_copy_code_button: true

heading_anchors: true

